### ISSUE TITLE
npe2 0.7.0 prevents building wheels

### ISSUE THREAD

**Issue by Schamschula** [napari/npe2#290]
* npe2 version: 0.7.0
* Python version: 3.11
* Operating System: macOS Ventura (13.4), arm64, MacPorts

### Description

After installing `py311-npe2 @0.7.0` I have run into build issues for any python package built from source. For packages that don't depend on npe2, I can deactivate npe2, but when building dependents, i.e. `napari` itself that isn't an option.

### What I Did

```
--->  Building napari
Executing:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_napari/napari/work/napari-0.4.17" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_napari/napari/work 
* Getting build dependencies for wheel...
/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
!!

        ********************************************************************************
        The license_file parameter is deprecated, use license_files instead.

        By 2023-Oct-30, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

!!
  parsed = self.parsers.get(option_name, lambda x: x)(value)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 496, in __init__
    _Distribution.__init__(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
    self.finalize_options()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 934, in finalize_options
    for ep in sorted(loaded, key=by_order):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 933, in <lambda>
    loaded = map(lambda e: e.load(), filtered)
                           ^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/__init__.py", line 9, in <module>
    from ._dynamic_plugin import DynamicPlugin
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/_dynamic_plugin.py", line 19, in <module>
    from ._plugin_manager import PluginManager
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/_plugin_manager.py", line 30, in <module>
    from ._command_registry import CommandRegistry
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/_command_registry.py", line 9, in <module>
    from .manifest import utils
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/manifest/__init__.py", line 1, in <module>
    from ._package_metadata import PackageMetadata
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/npe2/manifest/_package_metadata.py", line 14, in <module>
    class PackageMetadata(BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Command failed:  cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_napari/napari/work/napari-0.4.17" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_napari/napari/work 
Exit code: 1
Error: Failed to build napari: command execution failed
```

For some reason `python3.11/site-packages/npe2/__init__.py` is always imported. Why?

Note: I ran into this issue while building other dependencies of `napari`: `py311-numpydoc`, and `py311-tifffile`. I suppose this will happen for any other package.

P.S.: I cannot replicate the same error with Python 3.10, i.e. the install of `napari` and its dependents succeeded.

**Comment by tlambert03** [comment]
Are you trying to build something that depends on napari on python 3.11?  Napari doesn't support 3.11 yet

**Comment by Schamschula** [comment]
No, I was using Napari as an example of the error I'm seeing. I got exactly the same errors for py311-numpydoc, and py311-tifffile. I've been slowly enabling py311 for the dependencies I maintain to be ready when Napari does support 3.11.

The problem here is the interaction of npe2, and the Python build system. I guess I better disable the py311 subport until it's officially supported.

**Comment by tlambert03** [comment]
Yeah, I'm not quite sure what you're running into from the traceback provided. How exactly are you building here?  And _what_  are you building here?

Npe2 itself doesn't test python 3.11 (since there's no particular need at the moment since napari has a fair amount of work to do before it's ready)... so I'd say just wait until these packages officially support python 3.11 (not sure what you're running into with tifffile)

**Comment by Czaki** [comment]
It will be nice to see not napari error. 
Also, why did you build without isolation and which version of pydantic did you have installed? 
Whole log looks like setuptools try to collect metadata of installed packages. I do not know why they need to import all modules for it. But it rather looks like you have installed packages in incompatible versions in one environment. 



napari is close to 3.11 support https://github.com/napari/napari/pull/5439

**Comment by Schamschula** [comment]
I'm building using the MacPorts python infrastructure (PortGroup). 

I built against `py311-pydantic @1.10.8_0`, however I haven't pushed that to the MacPorts repo. The currently generally available version is `@1.9.0_0`.
